import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

type TranslationKey = string;
type Translations = Record<TranslationKey, string>;

const translations: Record<Language, Translations> = {
  en: {
    // Navigation
    'nav.welcome': 'Welcome to Garbet',
    'nav.sports': 'SPORTS',
    'nav.live': 'LIVE',
    'nav.jackpot': 'JACKPOT',
    'nav.new': 'NEW GAMES',
    'nav.slot': 'SLOT',
    'nav.liveGames': 'LIVE GAMES',
    'nav.virtualSports': 'VIRTUAL SPORTS',
    'nav.esports': 'E-SPORTS',
    'nav.login': 'LOGIN',
    'nav.register': 'REGISTER',
    'nav.signup': 'SIGN UP',

    // Hero
    'hero.new': 'NEW',
    'hero.title': 'COMPANY PRIVACY',
    'hero.subtitle': 'BREACH DETECTED',
    'hero.description': 'Writers accessible',
    'hero.legal': 'All operations and connections with our headquarters are completely legal and secure.',
    'hero.details': 'DETAILS',

    // Games
    'games.popular': 'Popular Games',
    'games.viewAll': 'View All',
    'games.play': 'PLAY',
    'games.featured': 'Featured Games',
    'games.playNow': 'Play Now',

    // Categories
    'cat.explore': 'EXPLORE',
    'cat.casino': 'Casino Games',
    'cat.casinoSub': 'Play Classic Games',
    'cat.slots': 'Slot Games',
    'cat.slotsSub': 'Spin & Win',
    'cat.live': 'Live Casino',
    'cat.liveSub': 'Real Dealers',
    'cat.sports': 'Sports Betting',
    'cat.sportsSub': 'Bet on Sports',
    'cat.jackpot': 'Progressive Jackpots',
    'cat.jackpotSub': 'Win Big',

    // Live Casino
    'live.title': 'Live Casino',
    'live.allTables': 'All Tables',
    'live.live': 'LIVE',
    'live.vip': 'VIP',
    'live.dealer': 'Dealer',
    'live.minBet': 'Min Bet',
    'live.maxBet': 'Max Bet',
    'live.joinTable': 'JOIN TABLE',

    // Sports
    'sports.sectionTitle': 'Live Matches',
    'sports.allMatches': 'All Matches',
    'sports.home': 'Home',
    'sports.draw': 'Draw',
    'sports.away': 'Away',
    'sports.startTime': 'Start Time',

    // Promos
    'promo.title': 'Promotions',
    'promo.viewAll': 'View All',
    'promo.welcome': 'Welcome Bonus',
    'promo.welcomeDesc': 'Get your first deposit bonus',
    'promo.daily': 'Daily Rewards',
    'promo.dailyDesc': 'Login every day for bonuses',
    'promo.cashback': 'Weekly Cashback',
    'promo.cashbackDesc': 'Get up to 10% back',
    'promo.vip': 'VIP Program',
    'promo.vipDesc': 'Exclusive rewards for VIP',
    'promo.seeDetails': 'See Details',

    // Footer
    'footer.payment': 'Payment Methods',
    'footer.about': 'About Us',
    'footer.aboutCompany': 'About Company',
    'footer.careers': 'Careers',
    'footer.news': 'News',
    'footer.partners': 'Partners',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact Us',
    'footer.responsible': 'Responsible Gaming',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.aml': 'AML Policy',
    'footer.kyc': 'KYC Policy',
    'footer.games': 'Games',
    'footer.casino': 'Casino',
    'footer.liveCasino': 'Live Casino',
    'footer.sportsbook': 'Sportsbook',
    'footer.virtualSports': 'Virtual Sports',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.liveSupport': '24/7 Live Support',
    'footer.alwaysHere': 'Always Here For You',
    'footer.copyright': '© 2026 Garbet. All rights reserved.',
    'footer.playResponsible': '18+ Play responsibly',
    'footer.license': 'License No: 8048/JAZ2020-013',
    'footer.paymentMethodsTitle': 'Payment Methods',
    'footer.description': 'Turkey\'s most reliable online betting and casino platform. At your service 7/24 with customer support.',
    'footer.aboutUs': 'About Us',
    'footer.whoWeAre': 'Who We Are',
    'footer.career': 'Career',
    'footer.press': 'Press',
    'footer.partnership': 'Partnership',
    'footer.help': 'Help',
    'footer.paymentMethods': 'Payment Methods',
    'footer.withdrawal': 'Withdrawal',
    'footer.responsibility': 'Responsibility',
    'footer.security': 'Security',
    'footer.termsOfUse': 'Terms of Use',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.bonusTerms': 'Bonus Terms',
    'footer.slotGames': 'Slot Games',
    'footer.sportsBetting': 'Sports Betting',
    'footer.eSports': 'E-Sports',
    'footer.responsibleGaming': '18+ Play responsibly',
    'footer.licenseNo': 'License No: 8048/JAZ2020-013',

    // Slot Games Page
    'slot.searchGame': 'Search Game',
    'slot.searchPlaceholder': 'Game name...',
    'slot.providers': 'Providers',
    'slot.features': 'Features',
    'slot.volatility': 'Volatility',
    'slot.low': 'Low',
    'slot.medium': 'Medium',
    'slot.high': 'High',
    'slot.newGame': 'NEW GAME',
    'slot.bannerTitle': 'BOUNTY HUNTER',
    'slot.bannerSubtitle': '100% Win Potential',
    'slot.bannerDesc': 'Try your luck in our new slot game and win big prizes!',
    'slot.playNow': 'PLAY NOW',
    'slot.details': 'DETAILS',
    'slot.jackpotTitle': 'JACKPOT',
    'slot.totalPool': 'Total Jackpot Pool',
    'slot.winners': 'Winners',
    'slot.thisMonth': 'This Month',
    'slot.biggest': 'Biggest',
    'slot.gamesFound': 'games found',
    'slot.loadMore': 'Load More',
    'slot.home': 'Home',
    'slot.all': 'All',
    'slot.popular': 'Popular',
    'slot.new': 'New',
    'slot.megaways': 'Megaways',
    'slot.bonusBuy': 'Bonus Buy',
    'slot.live': 'Live',
    'slot.tables': 'Tables',
    'slot.classic': 'Classic',
    'slot.filters': 'Filters',
    'slot.show': 'Show',
    'slot.hide': 'Hide',
    'slot.slotGames': 'SLOT GAMES',

    // Slot Games Page Additions
    'slotGames.title': 'Slot Games',
    'slotGames.subtitle': 'Spin to win amazing prizes and jackpots!',
    'slotGames.jackpotInfo': 'Progressive Jackpots Available',
    'slotGames.search': 'Search slot games...',
    'slotGames.jackpot': 'Jackpot Games',
    'slotGames.hot': 'Hot Games',
    'slotGames.new': 'New Games',
    'slotGames.allGames': 'All Games',

    // Live Casino Page
    'liveCasino.title': 'Live Casino',
    'liveCasino.subtitle': 'Play with real dealers in real-time!',
    'liveCasino.liveDealers': '32+ Live Dealers Online',
    'liveCasino.search': 'Search live casino games...',
    'liveCasino.featured': 'Featured Tables',
    'liveCasino.roulette': 'Live Roulette',
    'liveCasino.blackjack': 'Live Blackjack',
    'liveCasino.baccarat': 'Live Baccarat',

    // Sports Page
    'sports.title': 'Sports Betting',
    'sports.subtitle': 'Bet on your favorite sports and win big!',
    'sports.search': 'Search matches...',
    'sports.liveMatches': 'Live Matches',
    'sports.viewAll': 'View All',
    'sports.featuredTournaments': 'Featured Tournaments',
    'sports.matches': 'matches',
    'sports.upcomingMatches': 'Upcoming Matches',

    // TV Games Page
    'tvGames.title': 'TV Games',
    'tvGames.subtitle': 'Live TV betting games with instant results!',
    'tvGames.search': 'Search TV games...',
    'tvGames.liveGames': 'Live TV Games',

    // Promotions Page
    'promotions.title': 'Promotions & Bonuses',
    'promotions.subtitle': 'Amazing bonuses and rewards waiting for you!',
    'promotions.search': 'Search promotions...',
    'promotions.categories.all': 'All',
    'promotions.categories.welcome': 'Welcome',
    'promotions.categories.deposit': 'Deposit',
    'promotions.categories.cashback': 'Cashback',
    'promotions.categories.freespin': 'Free Spins',
    'promotions.categories.sports': 'Sports',
    'promotions.categories.casino': 'Casino',
    'promotions.categories.vip': 'VIP',

    // Authentication
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.register': 'Register',
    'auth.welcomeBack': 'Welcome back! Please login to your account.',
    'auth.createAccount': 'Create your account to get started',
    'auth.accountCredentials': 'Set up your account credentials',
    'auth.newMember': 'New member?',
    'auth.registerEasy': 'Register now, it\'s easy!',
    'auth.registrationStep': 'Registration Step',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.email': 'Email',
    'auth.firstName': 'First Name',
    'auth.middleName': 'Middle Name',
    'auth.surname': 'Surname',
    'auth.birthDate': 'Birth Date',
    'auth.country': 'Country',
    'auth.currency': 'Currency',
    'auth.city': 'City',
    'auth.address': 'Address',
    'auth.passportId': 'Passport / ID',
    'auth.gender': 'Gender',
    'auth.genderMale': 'Male',
    'auth.genderFemale': 'Female',
    'auth.genderOther': 'Other',
    'auth.phoneNumber': 'Phone number',
    'auth.promoCode': 'Promo code',
    'auth.over18Agreement': 'I am over 18 years of age and have accepted the',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.andThe': 'and the',
    'auth.generalTerms': 'General Terms & Conditions',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.signUpNow': 'Sign Up Now',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInNow': 'Sign In Now',
    'auth.contactSupport': 'Contact Support',
    'auth.or': 'OR',
    'auth.back': 'Back',
    'auth.next': 'Next',
    'auth.signingIn': 'Signing In...',
    'auth.registering': 'Registering...',
    'auth.loginSuccess': 'Login successful! Welcome back!',
    'auth.registrationSuccess': 'Registration successful! Welcome to Garbet!',
    'auth.fillAllFields': 'Please fill in all required fields',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordRequirements': 'Please meet all password requirements',
    'auth.acceptTerms': 'Please accept the terms and conditions',
    'auth.loginError': 'Login failed. Please check your credentials.',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.usernamePlaceholder': 'Enter your username',
    'auth.firstNamePlaceholder': 'Enter your first name',
    'auth.middleNamePlaceholder': 'Enter your middle name (optional)',
    'auth.surnamePlaceholder': 'Enter your surname',
    'auth.cityPlaceholder': 'Enter your city',
    'auth.selectCountry': 'Select your country',
    'auth.selectCurrency': 'Select your currency',
    'auth.passwordWeak': 'Weak',
    'auth.passwordMedium': 'Medium',
    'auth.passwordStrong': 'Strong',
    'auth.passwordMustInclude': 'Your password must include:',
    'auth.requireNumber': 'At least one digit',
    'auth.requireLength': 'Between 8-50 characters',
    'auth.requireNoSpaces': 'No spaces',
    'auth.requireLowerUpper': 'Lower and uppercase letters',
    'auth.requireEnglish': 'Only English characters',
    'auth.agreeToTerms': 'I agree to the',
    'auth.termsAndConditions': 'Terms & Conditions',

    // Game Features
    'feature.bonusBuy': 'Bonus Buy',
    'feature.freeSpins': 'Free Spins',
    'feature.jackpot': 'Jackpot',
    'feature.megaways': 'Megaways',
    'feature.multiplier': 'Multiplier',
    'feature.wild': 'Wild',
    'feature.scatter': 'Scatter',
    'feature.avalanche': 'Avalanche',

    // Badges
    'badge.new': 'NEW',
    'badge.hot': 'HOT',
    'badge.jackpot': 'JACKPOT',

    // Game Specific
    'game.credit': 'CREDIT',
    'game.bet': 'BET',
    'game.win': 'WIN',
    'game.payout': 'PAYOUT',
    'game.buyFeature': 'BUY FEATURE',
    'game.doubleChance': 'DOUBLE CHANCE FEATURE',
    'game.winChance': 'WIN CHANCE',
    'game.closed': 'CLOSED',
    'game.open': 'OPEN',
    'game.autoSpin': 'AUTO SPIN',
    'game.autoRounds': '5 ROUNDS AUTOMATIC',
    'game.rounds': 'ROUNDS',
    'game.holdSpace': 'HOLD SPACE FOR TURBO SPIN',
    'game.loading': 'LOADING',
    'game.tumbleWin': 'TUMBLE WIN',
  },
  tr: {
    // Navigation
    'nav.welcome': 'Garbet\'e Hoş Geldiniz',
    'nav.sports': 'SPOR',
    'nav.live': 'CANLI',
    'nav.jackpot': 'JACKPOT',
    'nav.new': 'YENİ ÇIKIŞ',
    'nav.slot': 'SLOT',
    'nav.liveGames': 'CANLI OYUN',
    'nav.virtualSports': 'SANAL SPORLAR',
    'nav.esports': 'E-SPOR',
    'nav.login': 'GİRİŞ',
    'nav.register': 'ÜYE OL',
    'nav.signup': 'KAYIT',

    // Hero
    'hero.new': 'YENİ',
    'hero.title': 'ŞİRKETİN GİZLİLİĞİNİ',
    'hero.subtitle': 'İHLAL ETMİŞTİR',
    'hero.description': 'YAZARLAR ULAŞILABİLİNEMEZ',
    'hero.legal': 'İşletim merkezi ile tüm halklar ve bağlantılar tamamen yasal ve güvenlidir.',
    'hero.details': 'DETAYLAR',

    // Games
    'games.popular': 'Popüler Oyunlar',
    'games.viewAll': 'Tümünü Gör',
    'games.play': 'OYNA',
    'games.featured': 'Öne Çıkan Oyunlar',
    'games.playNow': 'Şimdi Oyna',

    // Categories
    'cat.explore': 'KEŞFET',
    'cat.casino': 'Casino Oyunları',
    'cat.casinoSub': 'Klasik Oyunlar',
    'cat.slots': 'Slot Oyunları',
    'cat.slotsSub': 'Çevir & Kazan',
    'cat.live': 'Canlı Casino',
    'cat.liveSub': 'Gerçek Krupiyeler',
    'cat.sports': 'Spor Bahisleri',
    'cat.sportsSub': 'Spor Bahisleri',
    'cat.jackpot': 'Büyük Jackpotlar',
    'cat.jackpotSub': 'Büyük Kazan',

    // Live Casino
    'live.title': 'Canlı Casino',
    'live.allTables': 'Tüm Masalar',
    'live.live': 'CANLI',
    'live.vip': 'VIP',
    'live.dealer': 'Krupiye',
    'live.minBet': 'Min Bahis',
    'live.maxBet': 'Max Bahis',
    'live.joinTable': 'MASAYA KATIL',

    // Sports
    'sports.sectionTitle': 'Canlı Maçlar',
    'sports.allMatches': 'Tüm Maçlar',
    'sports.home': 'Ev Sahibi',
    'sports.draw': 'Beraberlik',
    'sports.away': 'Deplasman',
    'sports.startTime': 'Başlama',

    // Promos
    'promo.title': 'Promosyonlar',
    'promo.viewAll': 'Tümünü Gör',
    'promo.welcome': 'Hoş Geldin Bonusu',
    'promo.welcomeDesc': 'İlk yatırım bonusunuzu alın',
    'promo.daily': 'Günlük Ödüller',
    'promo.dailyDesc': 'Her gün giriş yapın bonuslar kazanın',
    'promo.cashback': 'Haftalık Cashback',
    'promo.cashbackDesc': '%10\'a kadar geri alın',
    'promo.vip': 'VIP Programı',
    'promo.vipDesc': 'VIP\'ler için özel ödüller',
    'promo.seeDetails': 'Detayları Gör',

    // Footer
    'footer.payment': 'Ödeme Yöntemleri',
    'footer.about': 'Hakkımızda',
    'footer.aboutCompany': 'Şirket Hakkında',
    'footer.careers': 'Kariyer',
    'footer.news': 'Haberler',
    'footer.partners': 'Ortaklar',
    'footer.support': 'Destek',
    'footer.helpCenter': 'Yardım Merkezi',
    'footer.faq': 'S.S.S',
    'footer.contact': 'İletişim',
    'footer.responsible': 'Sorumlu Oyun',
    'footer.legal': 'Yasal',
    'footer.terms': 'Şartlar & Koşullar',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.aml': 'AML Politikası',
    'footer.kyc': 'KYC Politikası',
    'footer.games': 'Oyunlar',
    'footer.casino': 'Casino',
    'footer.liveCasino': 'Canlı Casino',
    'footer.sportsbook': 'Spor Bahisleri',
    'footer.virtualSports': 'Sanal Sporlar',
    'footer.email': 'E-posta',
    'footer.phone': 'Telefon',
    'footer.liveSupport': '7/24 Canlı Destek',
    'footer.alwaysHere': 'Her Zaman Yanınızdayız',
    'footer.copyright': '© 2026 Garbet. Tüm hakları saklıdır.',
    'footer.playResponsible': '18+ Sorumluluk ile oynayın',
    'footer.license': 'Lisans No: 8048/JAZ2020-013',
    'footer.paymentMethodsTitle': 'Ödeme Yöntemleri',
    'footer.description': 'Türkiye\'nin en güvenilir çevrimiçi bahis ve casino platformu. 7/24 müşteri hizmetleri ile hizmetinizdeyiz.',
    'footer.aboutUs': 'Hakkımızda',
    'footer.whoWeAre': 'Kimiz',
    'footer.career': 'Kariyer',
    'footer.press': 'Basın',
    'footer.partnership': 'Ortaklık',
    'footer.help': 'Yardım',
    'footer.paymentMethods': 'Ödeme Yöntemleri',
    'footer.withdrawal': 'Para Çekme',
    'footer.responsibility': 'Sorumluluk',
    'footer.security': 'Güvenlik',
    'footer.termsOfUse': 'Kullanım Şartları',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.cookiePolicy': 'Çerez Politikası',
    'footer.bonusTerms': 'Bonus Şartları',
    'footer.slotGames': 'Slot Oyunları',
    'footer.sportsBetting': 'Spor Bahisleri',
    'footer.eSports': 'E-Spor',
    'footer.responsibleGaming': '18+ Sorumluluk ile oynayın',
    'footer.licenseNo': 'Lisans No: 8048/JAZ2020-013',

    // Slot Games Page
    'slot.searchGame': 'Oyun Ara',
    'slot.searchPlaceholder': 'Oyun adı...',
    'slot.providers': 'Sağlayıcılar',
    'slot.features': 'Özellikler',
    'slot.volatility': 'Volatilite',
    'slot.low': 'Düşük',
    'slot.medium': 'Orta',
    'slot.high': 'Yüksek',
    'slot.newGame': 'YENİ OYUN',
    'slot.bannerTitle': 'BOUNTY HUNTER',
    'slot.bannerSubtitle': '100% Kazanç Yaratın',
    'slot.bannerDesc': 'Yeni slot oyunumuzda şansınızı deneyin ve büyük ödüller kazanın!',
    'slot.playNow': 'ŞİMDİ OYNA',
    'slot.details': 'DETAYLAR',
    'slot.jackpotTitle': 'JACKPOT',
    'slot.totalPool': 'Toplam Jackpot Havuzu',
    'slot.winners': 'Kazanan',
    'slot.thisMonth': 'Bu Ay',
    'slot.biggest': 'En Büyük',
    'slot.gamesFound': 'oyun bulundu',
    'slot.loadMore': 'Daha Fazla Yükle',
    'slot.home': 'Ana Sayfa',
    'slot.all': 'Tümü',
    'slot.popular': 'Popüler',
    'slot.new': 'Yeni',
    'slot.megaways': 'Megaways',
    'slot.bonusBuy': 'Bonus Buy',
    'slot.live': 'Canlı',
    'slot.tables': 'Masalar',
    'slot.classic': 'Klasik',
    'slot.filters': 'Filtreler',
    'slot.show': 'Göster',
    'slot.hide': 'Gizle',
    'slot.slotGames': 'SLOT OYUNLARI',

    // Slot Games Page Additions
    'slotGames.title': 'Slot Oyunları',
    'slotGames.subtitle': 'İnanılmaz ödüller ve jackpotlar kazanmak için çevirin!',
    'slotGames.jackpotInfo': 'Artan Jackpotlar Mevcut',
    'slotGames.search': 'Slot oyunlarını ara...',
    'slotGames.jackpot': 'Jackpot Oyunlar',
    'slotGames.hot': 'Popüler Oyunlar',
    'slotGames.new': 'Yeni Oyunlar',
    'slotGames.allGames': 'Tüm Oyunlar',

    // Live Casino Page
    'liveCasino.title': 'Canlı Casino',
    'liveCasino.subtitle': 'Gerçek krupiyelerle gerçek zamanlı oynayın!',
    'liveCasino.liveDealers': '32+ Canlı Krupiye Çevrimiçi',
    'liveCasino.search': 'Canlı casino oyunlarını ara...',
    'liveCasino.featured': 'Öne Çıkan Masalar',
    'liveCasino.roulette': 'Canlı Rulet',
    'liveCasino.blackjack': 'Canlı Blackjack',
    'liveCasino.baccarat': 'Canlı Baccarat',

    // Sports Page
    'sports.title': 'Spor Bahisleri',
    'sports.subtitle': 'En sevdiğiniz sporlara bahis yapın ve büyük kazanın!',
    'sports.search': 'Maçları ara...',
    'sports.liveMatches': 'Canlı Maçlar',
    'sports.viewAll': 'Tümünü Gör',
    'sports.featuredTournaments': 'Öne Çıkan Turnuvalar',
    'sports.matches': 'maç',
    'sports.upcomingMatches': 'Yaklaşan Maçlar',

    // TV Games Page
    'tvGames.title': 'TV Oyunları',
    'tvGames.subtitle': 'Anında sonuçlarla canlı TV bahis oyunları!',
    'tvGames.search': 'TV oyunlarını ara...',
    'tvGames.liveGames': 'Canlı TV Oyunları',

    // Promotions Page
    'promotions.title': 'Promosyonlar & Bonuslar',
    'promotions.subtitle': 'Sizi bekleyen muhteşem bonuslar ve ödüller!',
    'promotions.search': 'Promosyonları ara...',
    'promotions.categories.all': 'Tümü',
    'promotions.categories.welcome': 'Hoş Geldin',
    'promotions.categories.deposit': 'Yatırım',
    'promotions.categories.cashback': 'Cashback',
    'promotions.categories.freespin': 'Bedava Spin',
    'promotions.categories.sports': 'Spor',
    'promotions.categories.casino': 'Casino',
    'promotions.categories.vip': 'VIP',

    // Authentication
    'auth.signIn': 'Giriş Yap',
    'auth.signUp': 'Kayıt Ol',
    'auth.register': 'Kayıt Ol',
    'auth.welcomeBack': 'Tekrar hoş geldiniz! Hesabınıza giriş yapın.',
    'auth.createAccount': 'Başlamak için hesabınızı oluşturun',
    'auth.accountCredentials': 'Hesap bilgilerinizi ayarlayın',
    'auth.newMember': 'Yeni üye misiniz?',
    'auth.registerEasy': 'Şimdi kaydolun, kolay!',
    'auth.registrationStep': 'Kayıt Adımı',
    'auth.username': 'Kullanıcı Adı',
    'auth.password': 'Şifre',
    'auth.confirmPassword': 'Şifreyi Onayla',
    'auth.email': 'E-posta',
    'auth.firstName': 'Adınız',
    'auth.middleName': 'Orta Adınız',
    'auth.surname': 'Soyadınız',
    'auth.birthDate': 'Doğum Tarihi',
    'auth.country': 'Ülke',
    'auth.currency': 'Para Birimi',
    'auth.city': 'Şehir',
    'auth.address': 'Adres',
    'auth.passportId': 'Pasaport / Kimlik',
    'auth.gender': 'Cinsiyet',
    'auth.genderMale': 'Erkek',
    'auth.genderFemale': 'Kadın',
    'auth.genderOther': 'Diğer',
    'auth.phoneNumber': 'Telefon Numarası',
    'auth.promoCode': 'Promosyon Kodu',
    'auth.over18Agreement': '18 yaşından büyük olduğumu ve',
    'auth.privacyPolicy': 'Gizlilik Politikasını',
    'auth.andThe': 've',
    'auth.generalTerms': 'Genel Şartlar & Koşulları kabul ettim',
    'auth.rememberMe': 'Beni Hatırla',
    'auth.forgotPassword': 'Şifremi Unuttum?',
    'auth.noAccount': "Hesabım yok?",
    'auth.signUpNow': 'Şimdi Kayıt Ol',
    'auth.alreadyHaveAccount': 'Zaten bir hesabım var?',
    'auth.signInNow': 'Şimdi Giriş Yap',
    'auth.contactSupport': 'Destek ile İletişime Geç',
    'auth.or': 'VEYA',
    'auth.back': 'Geri',
    'auth.next': 'İleri',
    'auth.signingIn': 'Giriş Yapılıyor...',
    'auth.registering': 'Kayıt Olunuyor...',
    'auth.loginSuccess': 'Giriş başarılı! Tekrar hoş geldiniz!',
    'auth.loginError': 'Giriş başarısız. Lütfen bilgilerinizi kontrol edin.',
    'auth.invalidCredentials': 'Geçersiz e-posta veya şifre',
    'auth.registrationSuccess': 'Kayıt başarılı! Garbet\'e hoş geldiniz!',
    'auth.fillAllFields': 'Lütfen tüm gerekli alanları doldurun',
    'auth.passwordMismatch': 'Şifreler eşleşmiyor',
    'auth.passwordRequirements': 'Lütfen tüm şifre gereksinimlerini karşılayınız',
    'auth.acceptTerms': 'Lütfen şartları ve koşulları kabul edin',
    'auth.usernamePlaceholder': 'Kullanıcı adınızı girin',
    'auth.firstNamePlaceholder': 'Adınızı girin',
    'auth.middleNamePlaceholder': 'Orta adınızı girin (opsiyonel)',
    'auth.surnamePlaceholder': 'Soyadınızı girin',
    'auth.cityPlaceholder': 'Şehirinizi girin',
    'auth.selectCountry': 'Ülkenizi seçin',
    'auth.selectCurrency': 'Para biriminizi seçin',
    'auth.passwordWeak': 'Zayıf',
    'auth.passwordMedium': 'Orta',
    'auth.passwordStrong': 'Güçlü',
    'auth.passwordMustInclude': 'Şifreniz şuları içermelidir:',
    'auth.requireNumber': 'En az bir rakam',
    'auth.requireLength': '8-50 karakter arasında',
    'auth.requireNoSpaces': 'Boşluk içermemeli',
    'auth.requireLowerUpper': 'Küçük ve büyük harfler',
    'auth.requireEnglish': 'Sadece İngilizce karakterler',
    'auth.agreeToTerms': 'Şartları ve koşulları kabul ediyorum',
    'auth.termsAndConditions': 'Şartlar & Koşullar',

    // Game Features
    'feature.bonusBuy': 'Bonus Al',
    'feature.freeSpins': 'Bedava Spinler',
    'feature.jackpot': 'Jackpot',
    'feature.megaways': 'Megaways',
    'feature.multiplier': 'Çarpan',
    'feature.wild': 'Joker',
    'feature.scatter': 'Dağılma',
    'feature.avalanche': 'Avalanche',

    // Badges
    'badge.new': 'YENİ',
    'badge.hot': 'POPÜLER',
    'badge.jackpot': 'JACKPOT',

    // Game Specific
    'game.credit': 'KREDİ',
    'game.bet': 'BAHİS',
    'game.win': 'KAZANÇ',
    'game.payout': 'KAZANIN',
    'game.buyFeature': 'SATIN ALMA ÖZELLİĞİ',
    'game.doubleChance': 'KAZANMA ŞANSINI İKİYE KATLAMA ÖZELLİĞİ',
    'game.winChance': 'KAZANIN',
    'game.closed': 'KAPALI',
    'game.open': 'AÇIK',
    'game.autoSpin': 'OTOMATİK OYUN',
    'game.autoRounds': '5 SEMBOL OTOMATİK',
    'game.rounds': 'ROUND',
    'game.holdSpace': 'TURBO SPİN İÇİN BOŞLUK TUŞUNA BASILI TUTUN',
    'game.loading': 'YÜKLENİYOR',
    'game.tumbleWin': 'DÜŞEN SEMBOLLER KAZANDIRIR',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}